# Generated by Django 6.0.3 on 2026-03-08 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254, verbose_name='Odbiorca')),
                ('subject', models.CharField(max_length=500, verbose_name='Temat')),
                ('body', models.TextField(verbose_name='Tresc')),
                ('status', models.CharField(choices=[('sent', 'Wyslany'), ('failed', 'Nieudany'), ('queued', 'W kolejce')], default='queued', max_length=10, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Komunikat bledu')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Wyslano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log emaila',
                'verbose_name_plural': 'Logi emaili',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_status', 'Status zamowienia'), ('order_new', 'Nowe zamowienie'), ('payment', 'Platnosc'), ('system', 'Systemowe'), ('promo', 'Promocja')], max_length=15, verbose_name='Typ')),
                ('title', models.CharField(max_length=300, verbose_name='Tytul')),
                ('message', models.TextField(verbose_name='Wiadomosc')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='Link')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Powiadomienie',
                'verbose_name_plural': 'Powiadomienia',
                'ordering': ['-created_at'],
            },
        ),
    ]
