# Generated by Django 6.0.3 on 2026-03-08 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Ikona (CSS class)')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejnosc')),
            ],
            options={
                'verbose_name': 'Kategoria komponentow',
                'verbose_name_plural': 'Kategorie komponentow',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SceneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena bazowa')),
                ('preview_image', models.ImageField(upload_to='templates/', verbose_name='Podglad')),
                ('model_3d_url', models.URLField(blank=True, verbose_name='URL modelu 3D')),
                ('width', models.DecimalField(decimal_places=2, default=10, max_digits=6, verbose_name='Szerokosc (m)')),
                ('depth', models.DecimalField(decimal_places=2, default=8, max_digits=6, verbose_name='Glebokosc (m)')),
                ('height', models.DecimalField(decimal_places=2, default=6, max_digits=6, verbose_name='Wysokosc (m)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Szablon sceny',
                'verbose_name_plural': 'Szablony scen',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('image', models.ImageField(upload_to='components/', verbose_name='Zdjecie')),
                ('specs', models.JSONField(blank=True, default=dict, verbose_name='Specyfikacja techniczna')),
                ('power_consumption', models.PositiveIntegerField(default=0, verbose_name='Pobor mocy (W)')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Waga (kg)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Dostepny')),
                ('max_quantity', models.PositiveIntegerField(default=100, verbose_name='Maks. ilosc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='configurator.componentcategory')),
            ],
            options={
                'verbose_name': 'Komponent',
                'verbose_name_plural': 'Komponenty',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('submitted', 'Zlozone'), ('reviewed', 'W recenzji'), ('quoted', 'Wycenione'), ('accepted', 'Zaakceptowane'), ('in_progress', 'W realizacji'), ('completed', 'Zrealizowane'), ('cancelled', 'Anulowane')], default='draft', max_length=15, verbose_name='Status')),
                ('event_name', models.CharField(max_length=300, verbose_name='Nazwa wydarzenia')),
                ('event_date', models.DateField(verbose_name='Data wydarzenia')),
                ('event_end_date', models.DateField(blank=True, null=True, verbose_name='Data zakonczenia')),
                ('event_location', models.CharField(max_length=500, verbose_name='Lokalizacja')),
                ('expected_audience', models.PositiveIntegerField(default=0, verbose_name='Przewidywana publicznosc')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kwota komponentow')),
                ('template_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cena szablonu')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rabat')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cena calkowita')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi klienta')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notatki wewnetrzne')),
                ('scene_data', models.JSONField(blank=True, default=dict, verbose_name='Dane konfiguracji sceny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_orders', to=settings.AUTH_USER_MODEL, verbose_name='Uzytkownik')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='configurator.scenetemplate', verbose_name='Szablon')),
            ],
            options={
                'verbose_name': 'Zamowienie sceny',
                'verbose_name_plural': 'Zamowienia scen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilosc')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('position_data', models.JSONField(blank=True, default=dict, verbose_name='Pozycja na scenie (x,y,z)')),
                ('notes', models.CharField(blank=True, max_length=500, verbose_name='Uwagi')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurator.component')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='configurator.order')),
            ],
            options={
                'verbose_name': 'Element zamowienia',
                'verbose_name_plural': 'Elementy zamowienia',
            },
        ),
    ]
