# Generated by Django 5.1.15 on 2026-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configurator", "0002_add_missing_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Moduł sceny",
                "verbose_name_plural": "Moduły sceny",
            },
        ),
        migrations.RemoveField(
            model_name="scenetemplate",
            name="model_3d_url",
        ),
        migrations.AlterField(
            model_name="component",
            name="color",
            field=models.CharField(
                blank=True,
                help_text="Kolor modułu na scenie",
                max_length=7,
                verbose_name="Kolor (hex)",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="icon_name",
            field=models.CharField(
                blank=True,
                help_text="Identyfikator ikony SVG w konfiguratorze (ufo, tree, laser, led, truss, fog)",
                max_length=50,
                verbose_name="Nazwa ikony",
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="components/", verbose_name="Zdjecie"
            ),
        ),
        migrations.AlterField(
            model_name="component",
            name="max_quantity",
            field=models.PositiveIntegerField(default=20, verbose_name="Maks. ilosc"),
        ),
        migrations.AlterField(
            model_name="componentcategory",
            name="color",
            field=models.CharField(
                default="#00ff88",
                help_text="Kolor kategorii w konfiguratorze",
                max_length=7,
                verbose_name="Kolor (hex)",
            ),
        ),
        migrations.AlterField(
            model_name="componentcategory",
            name="icon",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Ikona (emoji/klasa)"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Szkic"),
                    ("submitted", "Złożone"),
                    ("reviewed", "W recenzji"),
                    ("quoted", "Wycenione"),
                    ("accepted", "Zaakceptowane"),
                    ("in_progress", "W realizacji"),
                    ("completed", "Zrealizowane"),
                    ("cancelled", "Anulowane"),
                ],
                default="draft",
                max_length=15,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="position_data",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Pozycja na scenie (x,y)"
            ),
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="depth",
            field=models.DecimalField(
                decimal_places=2, default=15, max_digits=6, verbose_name="Glebokosc (m)"
            ),
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="height",
            field=models.DecimalField(
                decimal_places=2, default=8, max_digits=6, verbose_name="Wysokosc (m)"
            ),
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="preview_image",
            field=models.ImageField(
                blank=True, upload_to="templates/", verbose_name="Podglad"
            ),
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="thumbnail_url",
            field=models.URLField(
                blank=True,
                help_text="Zewnętrzny URL obrazka — używany gdy brak uploadu",
                verbose_name="URL miniaturki (zewn.)",
            ),
        ),
        migrations.AlterField(
            model_name="scenetemplate",
            name="width",
            field=models.DecimalField(
                decimal_places=2, default=20, max_digits=6, verbose_name="Szerokosc (m)"
            ),
        ),
    ]
