# Generated by Django 6.0.3 on 2026-03-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa')),
                ('location', models.CharField(max_length=500, verbose_name='Lokalizacja')),
                ('website', models.URLField(blank=True, verbose_name='Strona WWW')),
                ('logo', models.ImageField(blank=True, upload_to='festivals/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Festiwal',
                'verbose_name_plural': 'Festiwale',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Imie i nazwisko')),
                ('role', models.CharField(max_length=200, verbose_name='Rola')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('photo', models.ImageField(upload_to='team/', verbose_name='Zdjecie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('behance', models.URLField(blank=True, verbose_name='Behance')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejnosc')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Czlonek zespolu',
                'verbose_name_plural': 'Czlonkowie zespolu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Tytul')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Krotki opis')),
                ('client', models.CharField(blank=True, max_length=300, verbose_name='Klient')),
                ('date', models.DateField(verbose_name='Data realizacji')),
                ('category', models.CharField(choices=[('main_stage', 'Main Stage'), ('side_stage', 'Side Stage'), ('art_installation', 'Instalacja artystyczna'), ('lighting', 'Oswietlenie'), ('full_production', 'Pelna produkcja')], max_length=20, verbose_name='Kategoria')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyrozniany')),
                ('video_url', models.URLField(blank=True, verbose_name='URL wideo')),
                ('technologies', models.TextField(blank=True, verbose_name='Uzyty sprzet / technologie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.festival', verbose_name='Festiwal')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Zdjecie')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Podpis')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Okladka')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejnosc')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='Rola / firma')),
                ('content', models.TextField(verbose_name='Tresc')),
                ('avatar', models.ImageField(blank=True, upload_to='testimonials/', verbose_name='Awatar')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Ocena')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Widoczna')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Opinia',
                'verbose_name_plural': 'Opinie',
                'ordering': ['-created_at'],
            },
        ),
    ]
