# Generated by Django 6.0.3 on 2026-03-08 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('discount_type', models.CharField(choices=[('percentage', 'Procentowy'), ('fixed', 'Kwotowy')], max_length=10, verbose_name='Typ rabatu')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartosc rabatu')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Min. kwota zamowienia')),
                ('max_uses', models.PositiveIntegerField(default=0, verbose_name='Maks. uzyc')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Uzyto razy')),
                ('valid_from', models.DateTimeField(verbose_name='Wazny od')),
                ('valid_until', models.DateTimeField(verbose_name='Wazny do')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
            ],
            options={
                'verbose_name': 'Kupon',
                'verbose_name_plural': 'Kupony',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Klucz sesji')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Koszyk',
                'verbose_name_plural': 'Koszyki',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('image', models.ImageField(blank=True, upload_to='shop/categories/', verbose_name='Zdjecie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejnosc')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.productcategory', verbose_name='Kategoria nadrzedna')),
            ],
            options={
                'verbose_name': 'Kategoria produktu',
                'verbose_name_plural': 'Kategorie produktow',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Nazwa')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Opis')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Krotki opis')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena przed rabatem')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stan magazynowy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Wyrozniany')),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Waga (kg)')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Tagi (oddzielone przecinkiem)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.productcategory')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop/products/', verbose_name='Zdjecie')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Tekst alternatywny')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Glowne zdjecie')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejnosc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('paid', 'Oplacone'), ('processing', 'W realizacji'), ('shipped', 'Wyslane'), ('delivered', 'Dostarczone'), ('cancelled', 'Anulowane'), ('refunded', 'Zwrocone')], default='pending', max_length=15, verbose_name='Status')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Suma')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Koszt wysylki')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rabat')),
                ('shipping_name', models.CharField(max_length=200, verbose_name='Imie i nazwisko')),
                ('shipping_street', models.CharField(max_length=300, verbose_name='Ulica')),
                ('shipping_city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('shipping_postal_code', models.CharField(max_length=10, verbose_name='Kod pocztowy')),
                ('shipping_country', models.CharField(default='Polska', max_length=100, verbose_name='Kraj')),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Numer sledzenia')),
                ('notes', models.TextField(blank=True, verbose_name='Uwagi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zamowienie sklepowe',
                'verbose_name_plural': 'Zamowienia sklepowe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota')),
                ('currency', models.CharField(default='PLN', max_length=3, verbose_name='Waluta')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('payu', 'PayU'), ('p24', 'Przelewy24')], max_length=10, verbose_name='Dostawca')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('completed', 'Zrealizowana'), ('failed', 'Nieudana'), ('refunded', 'Zwrocona')], default='pending', max_length=10, verbose_name='Status')),
                ('external_id', models.CharField(blank=True, max_length=200, verbose_name='ID zewnetrzny')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadane')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='configurator.order')),
                ('shop_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shop.shoporder')),
            ],
            options={
                'verbose_name': 'Platnosc',
                'verbose_name_plural': 'Platnosci',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300, verbose_name='Nazwa produktu')),
                ('quantity', models.PositiveIntegerField(verbose_name='Ilosc')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena jednostkowa')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kwota')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.shoporder')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Ilosc')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
            options={
                'verbose_name': 'Element koszyka',
                'verbose_name_plural': 'Elementy koszyka',
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
